name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'Execute tests'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        allowed-conclusions: success
    - name: Wait for code style fixed
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'Commit changes'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        allowed-conclusions: success
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      env:
        REPOSITORY_PATH: ${{ vars.REPOSITORY_PATH }}
        PUBLIC_PATH: ${{ vars.PUBLIC_PATH }}
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        envs: REPOSITORY_PATH,PUBLIC_PATH
        script_stop: true
        script: |
          cd $REPOSITORY_PATH
          git pull
          rm -rf $PUBLIC_PATH/build
          cp -R $REPOSITORY_PATH/public/build $PUBLIC_PATH/build
          php artisan optimize:clear
