name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      env:
        REPOSITORY_PATH: ${{ vars.REPOSITORY_PATH }}
        PUBLIC_PATH: ${{ vars.PUBLIC_PATH }}
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        envs: REPOSITORY_PATH,PUBLIC_PATH
        script_stop: true
        script: |
          cd $REPOSITORY_PATH
          git pull
          rm -rf $PUBLIC_PATH/build
          cp -R $REPOSITORY_PATH/public/build $PUBLIC_PATH/build
          php artisan optimize:clear
